name: "ワクワクコースター" # 出し物のフォルダ名がデータ連携の結合キーも兼ねるので、設定は不要

description: "ポップなスニーカーのコースターに乗って洞窟の中を駆け回る。大迫力のイケボが聞こえてくる。最新技術を使った口臭の再現も！"

operating_hour_rules:
  # 可変長の配列なのでいくらでも設定できる
  # ルール1 → ルール2 → ルール3の順で解釈される

  timezone: "Asia/Tokyo" # 時刻にタイムゾーンを持たせると日程がズレる場合があるので全体で保持、IANAタイムゾーンデータベースを使用
  rules:
    # ルール1: 最優先(特定の日付範囲)
    - condition: "date_range"
      start_date: "2026-07-20"
      end_date: "2026-07-20"
      operating_hours:
      - ["9:00", "17:00"]

    - condition: "date_range"
      start_date: "2026-07-25"
      end_date: "2026-07-28"
      operating_hours:
      - ["9:00", "17:00"]
      - ["22:00", "0:20"] # 終了時刻が開始時刻より前なら翌日とみなす

    # ルール2: 優先(特定の曜日)
    - condition: "day_of_week"
      target: ["sat", "sun"]
      operating_hours:
      - ["10:00", "15:00"]
    
    # ルール3: 最下部(どれにも該当しない場合のフォールバック)
    - condition: "default"
      operating_hours:
      - ["09:00", "12:00"]
      - ["12:30", "16:00"]

duration:
  duration_seconds: 300
  is_approximate: true

  # `is_approximate` キーが `true` だと使える項目
  # ±n秒の形式
  margin_seconds: 120

location:
  lat: 35.8 # 登録された位置情報の精度に依存、大抵の場合はこれより高精度
  lng: 139.4
  floor: 1 # 建物の名前や教室名などは3Dモデルに登録されるので、位置情報や階数などの最小限の情報のみ保持

max_party_size: 2 # 1回で案内できる最大の人数

types:
  - "大きな音がする"
  - "フラッシュ"
  - "暗闇を進む"
  - "怖いキャラクターが登場"

features:
  - "雨の日も安心"
  - "揺れない"
  - "写真映え"

restrictions: "ご利用になる方は健康状態の良い方に限ります。同伴者の補助によっても安定した姿勢を保てない方はご利用になれません。"

accessibility: # システムであらかじめ用意されたものの中から選ぶ
  - "wheelchair_accessible" # 車椅子で利用可
  - "assistant_dog_allowed" # アシスタントドッグで利用可

available_ticket_slots:
  # 設定方法は営業時間と同じ
  
  timezone: "Asia/Tokyo"
  rules:
    - condition: "date_range"
      start_date: "2026-07-20"
      end_date: "2026-07-20"
      target_period: ["9:00", "9:30"] # 他の項目でも時間帯が"完全に"重複していたら、同一のものとして合計して処理される
      remaining_tickets: 5

    - condition: "date_range"
      start_date: "2026-07-25"
      end_date: "2026-07-28"
      target_period: ["9:02", "9:03"]
      remaining_tickets: 999

    - condition: "day_of_week"
      target: ["sat", "sun"]
      target_period: ["10:24", "10:24"] # この場合、10:24:00 ~ 10:24:59:... まで有効
      remaining_tickets: 777
    
    - condition: "default"
      target_period: ["9:00", "9:30"]
      remaining_tickets: 5
      
    - condition: "default" # 時間の枠ごとに分けて書く
      target_period: ["9:30", "10:00"] # 上の枠と9:30で被るがそれは仕様であり、システム上の問題はない
      remaining_tickets: 5

    - condition: "default" # 時間の枠ごとに分けて書く
      target_period: ["10:00", "10:30"] # 上の枠と9:30で被るがそれは仕様であり、システム上の問題はない
      remaining_tickets: 1

    - condition: "default" # 時間の枠ごとに分けて書く
      target_period: ["23:30", "0:00"] # このシステムは23:59までしか指定できない
      remaining_tickets: 9

      
