openapi: 3.1.0
info:
  title: System Settings API
  version: 1.0.0
  description: システム全体の共通設定やイベントIDの管理API

paths:
  /api/system/settings:
    $ref: './settings/openapi.yml'

  /api/system/event-id-mappings:
    $ref: './event_id_mappings/openapi.yml'
