openapi: 3.1.0
info:
  title: System Settings API
  version: 1.0.0
  description: システム全体の共通設定やイベントIDの管理API

paths:
  /system/settings:
    $ref: './settings/openapi.yml'

  /system/event-ids:
    $ref: './event_ids/openapi.yml'
