openapi: 3.1.0
info:
  title: Tickets API
  version: 1.0.0
  description: チケットの予約、認証、譲渡に関するAPI

paths:
  /api/tickets/reserve:
    post:
      $ref: './reserve.yml'

  /api/tickets/cancel:
    post:
      $ref: './cancel.yml'

  /api/tickets/authenticate:
    post:
      $ref: './authenticate.yml'

  /api/tickets/transfer:
    post:
      $ref: './transfer.yml'
