openapi: 3.1.0
info:
  title: reserve
  description: 指定した出し物の整理券を取得するAPI。
  version: 1.0.0
paths:
  /api/tickets/reserve:
    post:
      tags:
        - Tickets
      operationId: reserveTicket
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object

              properties:
                event_id:
                  $ref: "https://example.com/schemas/ticket.json#/properties/event_id"
                ticket_slot:
                  $ref: "https://example.com/schemas/ticket.json#/properties/ticket_slot"
                auth_type:
                  $ref: "https://example.com/schemas/ticket.json#/properties/auth_type"
              
              required:
                - event_id
                - ticket_slot
                - auth_type

      responses:

        '200':
          description: チケットの取得成功。
          content:
            application/json:
              schema:
                type: object
                properties:
                  ticket:
                    $ref: "https://example.com/schemas/ticket.json"
                  message:
                    type: string
                required:
                  - ticket
                  - message
                examples:
                  - ticket:
                      ticket_id: "5f2d28d2-5d18-21e8-f32b-dafb0a67babb"
                      event_id: "event-123"
                      ticket_slot:
                        start_time: "2026-08-01T15:00:00 09:00"
                        end_time: "2026-08-01T15:30:00 09:00"
                      auth_info: "JBSWY3DPEHPK3PXP"
                    message: "Ticket reserved successfully."

        '400':
          description: |
            不正なリクエスト。
            主にCLI等でAPIを直接叩いた場合を想定。
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                examples:
                  - message: "Invalid ticket slots."

        '409':
          description: |
            指定された枠にチケットが既に予約されている場合。
            主にCLI等でAPIを直接叩いた場合を想定。
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                examples:
                  - message: "User already has a ticket in this time slot."
