openapi: 3.1.0
info:
  title: reserve
  description: 指定した出し物の整理券を取得するAPI。
  version: 1.0.0
paths:
  /api/tickets/reserve:
    post:
      tags:
        - Tickets
      operationId: reserveTicket
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object

              properties:
                event_id:
                  $ref: "https://example.com/schemas/ticket.json#/properties/event_id"
                ticket_slot:
                  $ref: "https://example.com/schemas/ticket.json#/properties/ticket_slot"
              
              required:
                - event_id
                - ticket_slot

      responses:

        '200':
          description: |
            チケットのIDとメッセージ。
          content:
            application/json:
              schema:
                type: object
                properties:
                  ticket_id:
                    $ref: "https://example.com/schemas/ticket.json#/properties/ticket_id"
                  message:
                    type: string
                examples:
                  - ticket_id: "5f2d28d2-5d18-21e8-f32b-dafb0a67babb"
                    message: "Ticket reserved successfully."

        '400':
          description: |
            不正なリクエスト。
            主にCLI等でAPIを直接叩いた場合を想定。
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                examples:
                  - message: "Invalid ticket slots."

        '409':
          description: |
            指定された枠にチケットが既に予約されている場合。
            主にCLI等でAPIを直接叩いた場合を想定。
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                examples:
                  - message: "User already has a ticket in this time slot."
