openapi: 3.1.0
info:
  title: Events API
  version: 1.0.0
  description: 出し物に関するAPI

tags:
  - name: AdminEvents
    description: 管理者向けイベント操作

paths:
  /api/events/crowd-levels:
    get:
      $ref: './crowd_levels/get.yml'

  /api/events/operation-status:
    get:
      $ref: './operation_status/get.yml'
    put:
      $ref: './operation_status/update.yml'

  /api/events/profiles:
    get:
      $ref: './profiles/get.yml'

  /api/events/wait-times:
    get:
      $ref: './wait_times/get.yml'

  /api/events/site-info-transmission/crowd-level:
    $ref: './site_info_transmission/crowd_level.yml'

  /api/events/site-info-transmission/queue-group:
    $ref: './site_info_transmission/queue_group/openapi.yml'
