name: Build App (PWA)

on:
  push:
    paths:
      - 'apps/app/**'

# GitHub Pages へのデプロイに必要な権限を設定
permissions:
  pages: write
  id-token: write

jobs:
  build-and-deploy-for-dev:
    uses: ./.github/workflows/build-and-deploy-for-dev.yml
    with:
      directory: ./apps/app
