name: Build wait-time-info-transmitter

on:
  push:
    branches:
      - wait-time-info-transmitter
    paths:
      - 'apps/operations-side/site-info-transmitters/wait-time-info-transmitter/**'

defaults:
  run:
    working-directory: apps/operations-side/site-info-transmitters/wait-time-info-transmitter

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Build React App
        uses: mmedoo/build-react-on-push@v1.3
