name: Build Operations Side

on:
  push:
    paths:
      - 'apps/operations-side/**'

# GitHub Pages へのデプロイに必要な権限を設定
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      directory: ./apps/operations-side
